name: test_python

on: push

jobs:
    test_python:
      runs-on: ubuntu-latest
      steps:
        - run: |
            path = os.getpwd()
            echo $path
            echo 'do it well!'
        
