name: test_python

on: push

jobs:
    test_python:
      runs-on: ubuntu-latest
      steps:
        - run: |
            #cd 'ios'
            #path=$(pwd)
            path=$(ls)
            echo $path
        
