name: test_python

on: push

jobs:
    test_python:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: 'Setup python'
          uses: actions/setup-python@v1
          with:
            python-version: 3.8

        - name: 'install python dependency'
          run: pip install requests


        - name: 'auto genertor app event'
          run: |
            sh ./exce_event.sh ${chat_id}

          env:
            'chat_id': ${{secrets.APP_EVENT_CHAT_ID}}
