name: test_python

on: push

jobs:
    test_python:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: 'Setup python'
          uses: actions/setup_python@v1
          with:
            python-version: 3.8

        - name: 'working job'
           run: |
              echo 'well done'
        
